name: "Github pages"

on:
  push:
    branches:
      - storybook

jobs:
  gh_deploy:
    name: Deploy scenario
    runs-on: ubuntu-latest
    steps:
      # - name: Setup NodeJS v12
      #   uses: actions/setup-node@v1.1.0
      #   with:
      #     version:  12.x

      - name: Clean install dependencies
        run: npm install

      - name: Build static storybook
        run: npm run storybook:build

      - name: Copy build to gh-pages
        run: echo "Copying to gh_pages?"
